import { createApp } from 'vue'
import App from './App.vue'
import router from './router.js'
import 'katex/dist/katex.min.css'
import './shared/styles/tokens.css'
import './shared/styles/base.css'
import './shared/styles/layout.css'
import './shared/styles/responsive.css'
import './features/feedback/styles/feedback.css'
import './features/gallery/styles/gallery.css'
import './features/users/styles/userlist.css'
import './features/users/styles/dir.css'
import './features/napcat/styles/napcat.css'
import './features/debug/styles/debug.css'
import './features/stats/styles/stats.css'
import './features/settings/styles/function-settings.css'
import './features/groups/styles/group-strategy.css'
import './features/menu/styles/menu-panel.css'
import './features/logs/styles/errors.css'
import './features/logs/styles/send-logs.css'
import './features/logs/styles/event-logs.css'
import './shared/styles/polish.css'
import './shared/styles/app-shell.css'
import './features/chat/styles/chat.css'
import './features/loot/styles/loots.css'
import './features/settings/styles/bot-settings.css'

createApp(App).use(router).mount('#app')
