import { createApp } from 'vue'
import App from './App.vue'
import router from './router.js'
import 'katex/dist/katex.min.css'
import './styles/tokens.css'
import './styles/base.css'
import './styles/layout.css'
import './styles/responsive.css'
import './styles/feedback.css'
import './styles/gallery.css'
import './styles/userlist.css'
import './styles/dir.css'
import './styles/napcat.css'
import './styles/debug.css'
import './styles/stats.css'
import './styles/function-settings.css'
import './styles/group-strategy.css'
import './styles/menu-panel.css'
// ErrorReport 停用后仍需保留：发送日志、事件记录和机器人设置等页面复用这些样式。
import './styles/errors.css'
import './styles/send-logs.css'
import './styles/event-logs.css'
import './styles/polish.css'
import './styles/chat.css'
import './styles/loots.css'
import './styles/group-moderation.css'
import './styles/bot-settings.css'

createApp(App).use(router).mount('#app')
