import java.util.Properties
import java.text.SimpleDateFormat
import java.util.Date

plugins {
    `java-library`
    `maven-publish`
    application
    id("com.gradleup.shadow") version "9.3.1"
}

group = "top.yzljc"
version = "3.0.0-Release"
description = "AtriBot"

// 设置 Java 版本
java {
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    api(libs.io.javalin.javalin)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.cn.dev33.sa.token.sign)
    api(libs.com.google.guava.guava)
    api(libs.net.dankito.readability4j.readability4j)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.mysql.mysql.connector.j)
    api(libs.org.yaml.snakeyaml)
    api(libs.com.zaxxer.hikaricp)
    api(libs.org.apache.commons.commons.text)
    api(libs.org.jsoup.jsoup)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.cn.v6tail.lunar)
    api(libs.org.java.websocket.java.websocket)
    api(libs.ch.qos.logback.logback.classic)

    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("--enable-preview")
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

tasks.withType<JavaExec> {
    jvmArgs = listOf("--enable-preview")
}

val generateGitProperties by tasks.registering {
    val outputFile = layout.buildDirectory.file("generated/git/git.properties")
    outputs.file(outputFile)
    outputs.upToDateWhen { false }

    val projVersion = version.toString()

    doLast {
        val props = Properties()
        val sdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss z")
        props["git.build.time"] = sdf.format(Date())
        props["git.build.version"] = projVersion

        fun runGit(vararg args: String): String {
            return try {
                val process = ProcessBuilder("git", *args).start()
                val output = process.inputStream.bufferedReader().readText().trim()
                process.waitFor()
                if (process.exitValue() == 0 && output.isNotEmpty()) output else "unknown"
            } catch (_: Exception) {
                "unknown"
            }
        }

        props["git.commit.id.abbrev"] = runGit("rev-parse", "--short", "HEAD")
        props["git.commit.id.full"] = runGit("rev-parse", "HEAD")
        props["git.branch"] = runGit("rev-parse", "--abbrev-ref", "HEAD")

        val out = outputFile.get().asFile
        out.parentFile.mkdirs()
        out.writer(Charsets.UTF_8).use { props.store(it, "Generated by Gradle Native") }
    }
}

tasks.processResources {
    from(generateGitProperties)

    val nonFilteredExtensions = listOf("ttf", "woff", "woff2", "png", "jpg", "jpeg", "gif", "ico")
    val projVersion = project.version.toString()

    filesMatching("**/*") {
        val isBinary = nonFilteredExtensions.any { name.endsWith(".$it", ignoreCase = true) }
        val isGitProps = name == "git.properties"

        if (!isBinary && !isGitProps) {
            expand(
                "version" to projVersion
            )
        }
    }
}

tasks.jar {
    archiveClassifier.set("plain")
}

tasks.shadowJar {
    archiveClassifier.set("")

    manifest {
        attributes("Main-Class" to "top.yzljc.atribot.Atri")
    }

    exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")

    mergeServiceFiles()

    append("META-INF/org.slf4j.impl.StaticLoggerBinder")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}