package top.yzljc.atribot.event;

public enum EventType {
    NAPCAT_GROUP_MESSAGE,
    OFFICIAL_GROUP_MESSAGE,
    OFFICIAL_GROUP_AT_MESSAGE,
    OFFICIAL_C2C_MESSAGE,
    OFFICIAL_GUILD_CHANNEL,
    OFFICIAL_GUILD_DM,
    DISCORD_SLASH_COMMAND;
}