# Minecraft服务器数据监听端口
listen-port: 25566

# HTTPS对接Napcat的上报接收端口
qq-bot-port: 1234

# 哔哩哔哩视频查询用的Cookie
bilibili-cookie: "null"

# 管理员QQ账号
admin-uids:
  - 3199590352
  - 1948308

# Bot的QQ号（用来做数据排除）
bot-uid: 123456

# Debug用的QQ群号
debug-group: 123456

# 启用消息监听的群聊列表
message-spy-groups:
  - 123456
  - 234567

# Napcat HTTP 数据来源地址
# 必须是http://xxx.xxx.xxx:port格式
napcat-data-url: "http://localhost:12345"

# MYSQL数据库配置
mysql:
    host: "localhost"
    port: 3306
    database: "qq_bot"
    username: "qq_bot"
    password: "null"

# ManoDate推送群号（保密项目）
manosaba-group-id: 123456